export const cartStyles = {
  page: "min-h-screen bg-primary-container",
  topbar: "sticky top-0 z-50 bg-primary-container border-b border-outline/20 shadow-lg",
  topbarContent: "max-w-5xl mx-auto px-4 md:px-8 h-16 flex items-center gap-4",
  backLink: "text-on-surface/60 hover:text-on-surface transition-colors",
  backIcon: "material-symbols-outlined text-[28px]",
  headingContainer: "flex-1",
  heading: "text-headline-h3 font-bold text-on-surface leading-none",
  itemCount: "text-[12px] text-on-surface/40 mt-0.5",
  content: "max-w-5xl mx-auto px-4 md:px-8 py-8",
  empty: "flex flex-col items-center justify-center py-32 text-on-surface/40",
  emptyIcon: "material-symbols-outlined text-[80px] mb-4",
  emptyTitle: "text-body-lg mb-2",
  emptyDescription: "text-body-md text-on-surface/30 mb-8",
  catalogLink: "px-8 py-3 bg-secondary text-primary font-bold rounded-full hover:bg-secondary-fixed transition-all",
  grid: "grid lg:grid-cols-3 gap-8 items-start",
  itemList: "lg:col-span-2 space-y-4",
  itemCard: "bg-primary-container rounded-2xl border border-outline/20 p-4",
  itemRow: "flex gap-4",
  productImage: "w-24 h-24 rounded-xl bg-cover bg-center flex-shrink-0 border border-outline/20",
  itemInfo: "flex-1 min-w-0",
  itemHeader: "flex items-start justify-between gap-2",
  productInfo: "min-w-0",
  stockBadge: "inline-flex items-center gap-1 text-[11px] font-bold text-emerald-400 bg-emerald-400/10 px-2 py-0.5 rounded-full mb-1",
  stockDot: "w-1.5 h-1.5 rounded-full bg-emerald-400 inline-block",
  productTitle: "text-[14px] font-bold text-on-surface line-clamp-2 leading-snug",
  unitPrice: "text-[12px] text-on-surface/40 mt-0.5",
  variantBadges: "flex flex-wrap gap-1.5 mt-1.5",
  variantBadge: "inline-flex items-center gap-1 bg-surface-container text-on-surface/70 text-[11px] px-2 py-0.5 rounded-md",
  variantKey: "text-on-surface/40",
  deleteButton: "flex-shrink-0 p-1.5 rounded-lg text-on-surface/25 hover:text-red-400 hover:bg-red-400/10 transition-all",
  icon: "material-symbols-outlined text-[18px]",
  quantityRow: "flex items-center justify-between mt-3",
  quantityControl: "flex items-center bg-surface-container border border-outline/20 rounded-xl overflow-hidden",
  quantityButton: "w-9 h-9 flex items-center justify-center text-on-surface/50 hover:text-on-surface hover:bg-on-surface/10 transition-colors",
  quantityInput: "w-12 h-9 text-center text-on-surface text-[14px] font-bold bg-transparent border-x border-outline/20 focus:outline-none",
  subtotal: "text-right",
  subtotalLabel: "text-[11px] text-on-surface/30",
  subtotalValue: "text-[15px] font-bold text-secondary",
  noteContainer: "mt-3 pt-3 border-t border-outline/10",
  noteInput: "w-full bg-surface-container border border-outline/20 rounded-lg px-3 py-2 text-[12px] text-on-surface/70 placeholder:text-on-surface/25 focus:outline-none focus:border-secondary/50 transition-colors",
  clearContainer: "pt-2",
  clearButton: "text-[12px] text-on-surface/30 hover:text-red-400 transition-colors flex items-center gap-1",
  smallIcon: "material-symbols-outlined text-[14px]",
  confirmClear: "flex items-center gap-3 p-3 bg-red-500/10 border border-red-500/20 rounded-xl",
  confirmText: "text-[12px] text-red-300 flex-1",
  confirmButton: "text-[12px] font-bold text-red-400 hover:text-red-300 transition-colors",
  cancelButton: "text-[12px] text-on-surface/40 hover:text-on-surface transition-colors",
  itemCardExiting: "bg-primary-container rounded-2xl border border-red-500/20 p-4 transition-all duration-400 opacity-0 -translate-x-12 scale-90 blur-[2px]",
  itemCardEntering: "bg-primary-container rounded-2xl border border-outline/20 p-4 transition-all duration-300 opacity-100 translate-x-0 scale-100 blur-0",
  itemCardPending: "bg-primary-container rounded-2xl border border-red-500/15 p-4 transition-all duration-500 opacity-60 scale-[0.98] relative overflow-hidden",
  undoToast: "fixed top-6 left-1/2 -translate-x-1/2 z-[200] w-full max-w-sm px-4",
  undoToastEntering: "fixed top-6 left-1/2 -translate-x-1/2 z-[200] w-full max-w-sm px-4 animate-slideDownFromTop",
  undoToastExiting: "fixed top-6 left-1/2 -translate-x-1/2 z-[200] w-full max-w-sm px-4 animate-slideUpToTop",
  undoToastBox: "bg-primary-container border border-outline/20 rounded-2xl shadow-2xl overflow-hidden max-w-sm w-full",
  undoToastContent: "flex flex-col items-center gap-1 px-5 pt-4 pb-2 text-center",
  undoToastText: "text-[13px] text-on-surface/50",
  undoToastButton: "px-6 py-2 mb-4 rounded-xl bg-secondary/15 border border-secondary/30 text-secondary font-bold text-[13px] hover:bg-secondary/25 transition-all",
  undoToastProgress: "h-[3px] bg-surface-container w-full",
  undoToastProgressBar: "h-full bg-secondary/60 w-full origin-left animate-progressShrink",
  summaryColumn: "lg:col-span-1",
  summary: "bg-primary-container rounded-2xl border border-outline/20 p-6 sticky top-24 space-y-4",
  summaryTitle: "text-[13px] font-semibold text-on-surface/70",
  summaryItems: "space-y-2",
  summaryItem: "flex justify-between text-[12px]",
  summaryItemBlock: "",
  summaryVariants: "flex flex-wrap gap-1 mt-1",
  summaryVariantTag: "inline-flex items-center gap-1 bg-surface-container text-on-surface/40 text-[10px] px-1.5 py-0.5 rounded",
  summaryVariantKey: "text-on-surface/25",
  summaryItemName: "text-on-surface/50 truncate mr-2 leading-relaxed",
  mutedQuantity: "text-on-surface/30",
  summaryItemPrice: "text-on-surface/80 font-medium flex-shrink-0",
  dividerSection: "border-t border-outline/20 pt-3 space-y-2",
  summaryRow: "flex justify-between text-[12px]",
  label: "text-on-surface/50",
  price: "text-on-surface/80 font-medium",
  shipping: "text-on-surface/40 italic",
  totalSection: "border-t border-outline/20 pt-3",
  totalRow: "flex justify-between items-center",
  totalLabel: "text-[13px] font-semibold text-on-surface",
  totalPrice: "text-[20px] font-bold text-secondary",
  totalNotice: "text-[11px] text-on-surface/30 mt-1",
  checkoutButton: "w-full py-4 rounded-xl bg-secondary text-primary font-bold hover:bg-secondary-fixed transition-all flex items-center justify-center gap-2 text-[14px]",
  checkoutIcon: "material-symbols-outlined text-[20px]",
  continueLink: "w-full py-3 rounded-xl border border-outline/20 text-on-surface/50 hover:text-on-surface hover:border-outline transition-all text-[13px] flex items-center justify-center gap-2",
  trustSection: "border-t border-outline/20 pt-4",
  trustGrid: "grid grid-cols-3 gap-2 text-center",
  trustItem: "flex flex-col items-center gap-1",
  trustIcon: "material-symbols-outlined text-[20px] text-on-surface/30",
  trustText: "text-[10px] text-on-surface/30 leading-tight",
  popupOverlay: "fixed inset-0 z-[250] flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm",
  popupBox: "relative bg-primary-container border border-outline/20 rounded-2xl shadow-2xl max-w-sm w-full text-center overflow-hidden",
  popupImageWrap: "w-20 h-20 rounded-xl mx-auto mb-4 overflow-hidden border border-outline/20 shadow-lg",
  popupImage: "w-full h-full bg-cover bg-center",
  popupTitle: "text-[16px] font-bold text-on-surface mb-2",
  popupDesc: "text-[13px] text-on-surface/50 mb-5 leading-relaxed",
  popupActions: "flex gap-3",
  popupCancel: "flex-1 py-3 rounded-xl border border-outline/20 text-on-surface/50 text-[13px] font-medium hover:text-on-surface hover:border-outline transition-all",
  popupConfirm: "flex-1 py-3 rounded-xl bg-red-500/20 border border-red-400/30 text-red-400 text-[13px] font-bold hover:bg-red-500/30 transition-all flex items-center justify-center gap-1.5",
  pendingTimer: "absolute bottom-0 left-0 right-0 h-[3px] bg-red-500/10 overflow-hidden",
  pendingTimerBar: "h-full bg-red-400/60 w-full origin-left animate-progressShrink",
} as const;
