import type { Config } from "tailwindcss";
import containerQueries from "@tailwindcss/container-queries";
import forms from "@tailwindcss/forms";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary-container": "#4f3c00",
        "primary-fixed-dim": "#c6d0d6",
        "secondary-fixed-dim": "#e7bd4b",
        "text-body": "#3d4a53",
        "surface-container-highest": "#e3e9ec",
        "on-primary": "#ffffff",
        "on-tertiary-fixed-variant": "#514537",
        "inverse-surface": "#303031",
        "inverse-on-surface": "#f3f0f0",
        "on-secondary": "#1a2228",
        "on-tertiary-container": "#958675",
        "outline-variant": "#c4c7ca",
        "secondary-800": "#b78700",
        "on-primary-fixed": "#151d22",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed-variant": "#5b4300",
        "surface": "#f9fbfc",
        "tertiary-fixed-dim": "#d6c3b1",
        "secondary-container": "#ebbc36",
        "on-primary-container": "#e4ebee",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "secondary-50": "#fff8e5",
        "surface-container": "#edf1f3",
        "surface-container-high": "#e7edef",
        "primary-fixed": "#e4ebee",
        "primary-100": "#dce5e9",
        "tertiary-container": "#291f13",
        "tertiary": "#100802",
        "on-tertiary-fixed": "#231a0e",
        "tertiary-fixed": "#f3dfcc",
        "on-surface": "#1a2228",
        "primary-700": "#26323a",
        "surface-tint": "#52616a",
        "on-surface-variant": "#52606a",
        "primary": "#1a2228",
        "error": "#ba1a1a",
        "background": "#1a2228",
        "primary-container": "#26323a",
        "on-primary-fixed-variant": "#44535c",
        "secondary": "#dba501",
        "on-secondary-fixed": "#2c2100",
        "surface-variant": "#e3e9ec",
        "inverse-primary": "#c6d0d6",
        "on-background": "#f6f8f9",
        "surface-container-lowest": "#ffffff",
        "danger": "#c0392b",
        "bg-subtle": "#f4f7f8",
        "surface-dim": "#d8e0e4",
        "on-error-container": "#93000a",
        "surface-container-low": "#f7f9fa",
        "success": "#1e8e5a",
        "surface-bright": "#ffffff",
        "secondary-fixed": "#f4d36b",
        "outline": "#75838c",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "container-max": "1280px",
        "section-gap-mobile": "56px",
        "margin-x-desktop": "64px",
        "section-gap-desktop": "96px",
        "margin-x-mobile": "24px",
        "gutter": "24px",
      },
      fontFamily: {
        "display-hero-mobile": ["Plus Jakarta Sans"],
        "body-lg": ["Inter"],
        "headline-h3": ["Plus Jakarta Sans"],
        "headline-h2": ["Plus Jakarta Sans"],
        "label-sm": ["Inter"],
        "eyebrow": ["Plus Jakarta Sans"],
        "headline-h1": ["Plus Jakarta Sans"],
        "body-md": ["Inter"],
        "display-hero": ["Plus Jakarta Sans"],
      },
      fontSize: {
        "display-hero-mobile": ["40px", { lineHeight: "1.2", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-h3": ["20px", { lineHeight: "1.3", fontWeight: "600" }],
        "headline-h2": ["28px", { lineHeight: "1.2", fontWeight: "600" }],
        "label-sm": ["14px", { lineHeight: "1.4", letterSpacing: "0.02em", fontWeight: "500" }],
        "eyebrow": ["14px", { lineHeight: "1.2", letterSpacing: "0.1em", fontWeight: "700" }],
        "headline-h1": ["36px", { lineHeight: "1.2", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "display-hero": ["56px", { lineHeight: "1.1", fontWeight: "700" }],
      },
    },
  },
  plugins: [forms, containerQueries],
};
export default config;
