import type { Config } from "tailwindcss";
import containerQueries from "@tailwindcss/container-queries";
import forms from "@tailwindcss/forms";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/frontend/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/features/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // ── All values now reference CSS variables so light/dark
        // switching is driven purely by :root vs .dark token swaps.
        "on-secondary-container": "var(--color-on-secondary-container)",
        "primary-fixed-dim": "var(--color-primary-fixed-dim)",
        "secondary-fixed-dim": "var(--color-secondary-fixed-dim)",
        "text-body": "var(--color-text-body)",
        "surface-container-highest": "var(--color-surface-container-highest)",
        "on-primary": "var(--color-on-primary)",
        "on-tertiary-fixed-variant": "var(--color-on-tertiary-fixed-variant)",
        "inverse-surface": "var(--color-inverse-surface)",
        "inverse-on-surface": "var(--color-inverse-on-surface)",
        "on-secondary": "var(--color-on-secondary)",
        "on-tertiary-container": "var(--color-on-tertiary-container)",
        "outline-variant": "var(--color-outline-variant)",
        "secondary-800": "var(--color-secondary-800)",
        "on-primary-fixed": "var(--color-on-primary-fixed)",
        "on-tertiary": "var(--color-on-tertiary)",
        "on-secondary-fixed-variant": "var(--color-on-secondary-fixed-variant)",
        "surface": "var(--color-surface)",
        "tertiary-fixed-dim": "var(--color-tertiary-fixed-dim)",
        "secondary-container": "var(--color-secondary-container)",
        "on-primary-container": "var(--color-on-primary-container)",
        "on-error": "var(--color-on-error)",
        "error-container": "var(--color-error-container)",
        "secondary-50": "var(--color-secondary-50)",
        "surface-container": "var(--color-surface-container)",
        "surface-container-high": "var(--color-surface-container-high)",
        "primary-fixed": "var(--color-primary-fixed)",
        "primary-100": "var(--color-primary-100)",
        "tertiary-container": "var(--color-tertiary-container)",
        "tertiary": "var(--color-tertiary)",
        "on-tertiary-fixed": "var(--color-on-tertiary-fixed)",
        "tertiary-fixed": "var(--color-tertiary-fixed)",
        "on-surface": "var(--color-on-surface)",
        "primary-700": "var(--color-primary-700)",
        "surface-tint": "var(--color-surface-tint)",
        "on-surface-variant": "var(--color-on-surface-variant)",
        "primary": "var(--color-primary)",
        "error": "var(--color-error)",
        "background": "var(--color-background)",
        "primary-container": "var(--color-primary-container)",
        "on-primary-fixed-variant": "var(--color-on-primary-fixed-variant)",
        "secondary": "var(--color-secondary)",
        "on-secondary-fixed": "var(--color-on-secondary-fixed)",
        "surface-variant": "var(--color-surface-variant)",
        "inverse-primary": "var(--color-inverse-primary)",
        "on-background": "var(--color-on-background)",
        "surface-container-lowest": "var(--color-surface-container-lowest)",
        "danger": "var(--color-danger)",
        "bg-subtle": "var(--color-bg-subtle)",
        "surface-dim": "var(--color-surface-dim)",
        "on-error-container": "var(--color-on-error-container)",
        "surface-container-low": "var(--color-surface-container-low)",
        "success": "var(--color-success)",
        "surface-bright": "var(--color-surface-bright)",
        "secondary-fixed": "var(--color-secondary-fixed)",
        "outline": "var(--color-outline)",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "container-max": "1280px",
        "section-gap-mobile": "56px",
        "margin-x-desktop": "64px",
        "section-gap-desktop": "96px",
        "margin-x-mobile": "24px",
        "gutter": "24px",
      },
      fontFamily: {
        "display-hero-mobile": ["Plus Jakarta Sans"],
        "body-lg": ["Inter"],
        "headline": ["Plus Jakarta Sans"],
        "headline-h3": ["Plus Jakarta Sans"],
        "headline-h2": ["Plus Jakarta Sans"],
        "label-sm": ["Inter"],
        "eyebrow": ["Plus Jakarta Sans"],
        "headline-h1": ["Plus Jakarta Sans"],
        "body-md": ["Inter"],
        "display-hero": ["Plus Jakarta Sans"],
      },
      fontSize: {
        "display-hero-mobile": ["40px", { lineHeight: "1.2", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-h3": ["20px", { lineHeight: "1.3", fontWeight: "600" }],
        "headline-h2": ["28px", { lineHeight: "1.2", fontWeight: "600" }],
        "label-sm": ["14px", { lineHeight: "1.4", letterSpacing: "0.02em", fontWeight: "500" }],
        "eyebrow": ["14px", { lineHeight: "1.2", letterSpacing: "0.1em", fontWeight: "700" }],
        "headline-h1": ["36px", { lineHeight: "1.2", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "display-hero": ["56px", { lineHeight: "1.1", fontWeight: "700" }],
      },
    },
  },
  plugins: [forms, containerQueries],
};
export default config;
