import type { Invoice, Karyawan, TransaksiKas } from "./types";

const DAY = 24 * 60 * 60 * 1000;

const hariLalu = (jumlah: number) =>
  new Date(Date.now() - jumlah * DAY).toISOString().slice(0, 10);

export const transaksiKasAwal: TransaksiKas[] = [
  {
    id: "TRX-001",
    tanggal: hariLalu(52),
    jenis: "kas_masuk",
    uraian: "DP Proyek Kanopi Kantor Nganyang",
    kategori: "Dll",
    posProyek: "Nganyang",
    person: "CV Karya Baja Malang",
    nominal: 450_000_000,
    noNota: "INV/2026/091",
    bukti: "kuitansi_dp_kanopi.png",
    sumber: "termin",
    refId: "INV-2026-091",
  },
  {
    id: "TRX-002",
    tanggal: hariLalu(45),
    jenis: "kas_keluar",
    uraian: "Beli alumunium sheet 1,2 mm",
    kategori: "Alat & Bahan",
    posProyek: "Nganyang",
    person: "CV Karya Baja Malang",
    nominal: 87_500_000,
    noNota: "BKB-4471",
    bukti: "nota_belanja_alumunium.png",
    sumber: "termin",
    refId: "INV-2026-091",
  },
  {
    id: "TRX-003",
    tanggal: hariLalu(41),
    jenis: "kas_beredar",
    uraian: "Bon BBM dumping site",
    kategori: "BBM",
    posProyek: "Nganyang",
    person: "Ahmad Fauzi",
    nominal: 2_500_000,
    noNota: "",
    bukti: "kartu_bon_bbm.jpg",
    sumber: "manual",
    refId: "",
  },
  {
    id: "TRX-004",
    tanggal: hariLalu(38),
    jenis: "kas_keluar",
    uraian: "Pulrik listrik proyek 3 fasa",
    kategori: "Telpon & Listrik",
    posProyek: "Nganyang",
    person: "PLN",
    nominal: 12_750_000,
    noNota: "PLN-88213",
    bukti: "bukti_pembayaran_pln.png",
    sumber: "manual",
    refId: "",
  },
  {
    id: "TRX-005",
    tanggal: hariLalu(33),
    jenis: "kas_keluar",
    uraian: "Fee marketing iklan media lokal",
    kategori: "Fee Marketing",
    posProyek: "Kantor",
    person: "UD Berkah Mandiri",
    nominal: 15_000_000,
    noNota: "MKT-2026-118",
    bukti: "invoice_fee_marketing.pdf",
    sumber: "manual",
    refId: "",
  },
  {
    id: "TRX-006",
    tanggal: hariLalu(30),
    jenis: "kas_keluar",
    uraian: "Konsumsi rapat coordination lapangan",
    kategori: "Konsumsi",
    posProyek: "Kantor",
    person: "Katering Bu Yatmi",
    nominal: 3_450_000,
    noNota: "KY-221",
    bukti: "nota_katering.png",
    sumber: "manual",
    refId: "",
  },
  {
    id: "TRX-007",
    tanggal: hariLalu(28),
    jenis: "kas_masuk",
    uraian: "Termin 1 Proyek Partisi Karang Ploso",
    kategori: "Dll",
    posProyek: "Karang Ploso",
    person: "PT Alumex Indonesia",
    nominal: 275_000_000,
    noNota: "INV/2026/102",
    bukti: "kuitansi_termin1.png",
    sumber: "termin",
    refId: "INV-2026-102",
  },
  {
    id: "TRX-008",
    tanggal: hariLalu(25),
    jenis: "kas_beredar",
    uraian: "Bontransport material ke Jasinga",
    kategori: "Transportasi",
    posProyek: "SR Jasinga",
    person: "Bambang Sutrisno",
    nominal: 4_200_000,
    noNota: "",
    bukti: "surat_jalan.jpg",
    sumber: "manual",
    refId: "",
  },
  {
    id: "TRX-009",
    tanggal: hariLalu(21),
    jenis: "kas_keluar",
    uraian: "Servis forklift dan ganti oli",
    kategori: "Pemeliharaan",
    posProyek: "Karang Ploso",
    person: "Sewa Alat Berat Sejahtera",
    nominal: 6_800_000,
    noNota: "SAB-0912",
    bukti: "nota_servis_forklift.pdf",
    sumber: "manual",
    refId: "",
  },
  {
    id: "TRX-010",
    tanggal: hariLalu(18),
    jenis: "kas_keluar",
    uraian: "Pembelian ATK dan alat tulis kantor",
    kategori: "ATK",
    posProyek: "Kantor",
    person: "Toko Bangunan Jaya",
    nominal: 1_950_000,
    noNota: "TBJ-3340",
    bukti: "nota_atk.png",
    sumber: "manual",
    refId: "",
  },
  {
    id: "TRX-011",
    tanggal: hariLalu(15),
    jenis: "kas_keluar",
    uraian: "BBM genset proyek SR Nganjuk",
    kategori: "BBM",
    posProyek: "SR Nganjuk",
    person: "Pertamina",
    nominal: 9_300_000,
    noNota: "PRT-77120",
    bukti: "struk_pom.png",
    sumber: "manual",
    refId: "",
  },
  {
    id: "TRX-012",
    tanggal: hariLalu(12),
    jenis: "kas_keluar",
    uraian: "Konsumsi makancrew harian",
    kategori: "Konsumsi",
    posProyek: "SR Nganjuk",
    person: "Warung Bu Sri",
    nominal: 2_700_000,
    noNota: "",
    bukti: "bon_makan.png",
    sumber: "manual",
    refId: "",
  },
  {
    id: "TRX-013",
    tanggal: hariLalu(9),
    jenis: "kas_masuk",
    uraian: "DP Instalasi AC Kantsel Rajawali",
    kategori: "Dll",
    posProyek: "Kantor",
    person: "UD Berkah Mandiri",
    nominal: 180_000_000,
    noNota: "INV/2026/108",
    bukti: "kuitansi_dp_ac.png",
    sumber: "termin",
    refId: "INV-2026-108",
  },
  {
    id: "TRX-014",
    tanggal: hariLalu(7),
    jenis: "kas_keluar",
    uraian: "Gajiinharian 6 kuli borongan",
    kategori: "Dll",
    posProyek: "Karang Ploso",
    person: "Tim Borongan Karang Ploso",
    nominal: 21_600_000,
    noNota: "",
    bukti: "daftar_hadir.png",
    sumber: "payroll",
    refId: "PAY-2026-09",
  },
  {
    id: "TRX-015",
    tanggal: hariLalu(6),
    jenis: "kas_beredar",
    uraian: "Bon ATK lapangan",
    kategori: "ATK",
    posProyek: "SR Nganjuk",
    person: "Dedi Prasetyo",
    nominal: 1_150_000,
    noNota: "",
    bukti: "kartu_bon_atk.jpg",
    sumber: "manual",
    refId: "",
  },
  {
    id: "TRX-016",
    tanggal: hariLalu(4),
    jenis: "kas_keluar",
    uraian: "Ganti genset dan aki proyek",
    kategori: "Pemeliharaan",
    posProyek: "SR Jasinga",
    person: "CV Mitra Sejahtera",
    nominal: 4_350_000,
    noNota: "MS-0091",
    bukti: "nota_genset.png",
    sumber: "manual",
    refId: "",
  },
  {
    id: "TRX-017",
    tanggal: hariLalu(2),
    jenis: "kas_keluar",
    uraian: "Tolak pasak dan bahanISI",
    kategori: "Alat & Bahan",
    posProyek: "SR Jasinga",
    person: "Toko Bangunan Jaya",
    nominal: 7_800_000,
    noNota: "TBJ-3399",
    bukti: "nota_tokok.png",
    sumber: "manual",
    refId: "",
  },
  {
    id: "TRX-018",
    tanggal: hariLalu(1),
    jenis: "kas_masuk",
    uraian: "Termin 1 Revisi Dinding SR Jasinga",
    kategori: "Dll",
    posProyek: "SR Jasinga",
    person: "CV Karya Baja Malang",
    nominal: 96_000_000,
    noNota: "INV/2026/110",
    bukti: "kuitansi_termin1_jasinga.png",
    sumber: "termin",
    refId: "INV-2026-110",
  },
];

export const invoiceAwal: Invoice[] = [
  {
    id: "INV-2026-091",
    nomor: "091/ALU/2026",
    tanggal: hariLalu(52),
    pihak: "Kontraktor",
    nama: "CV Karya Baja Malang",
    proyek: "Kanopi Kantor Nganyang",
    posProyek: "Nganyang",
    uraian: "Pemasangan kanopi dan rangka baja galvanis",
    termin: [
      { id: "T1", label: "DP 30%", tanggal: hariLalu(52), jatuhTempo: hariLalu(52), nominal: 450_000_000, lunas: true },
      { id: "T2", label: "Termin 1 40%", tanggal: hariLalu(20), jatuhTempo: hariLalu(6), nominal: 600_000_000, lunas: false },
      { id: "T3", label: "Termin 2 25%", tanggal: hariLalu(-10), jatuhTempo: hariLalu(10), nominal: 375_000_000, lunas: false },
      { id: "T4", label: "Retensi 5%", tanggal: hariLalu(52), jatuhTempo: hariLalu(90), nominal: 75_000_000, lunas: false },
    ],
  },
  {
    id: "INV-2026-102",
    nomor: "102/ALU/2026",
    tanggal: hariLalu(30),
    pihak: "Kontraktor",
    nama: "PT Alumex Indonesia",
    proyek: "Partisi Kaca Karang Ploso",
    posProyek: "Karang Ploso",
    uraian: "Supply dan pemasangan partisi kaca offices",
    termin: [
      { id: "T1", label: "DP 30%", tanggal: hariLalu(30), jatuhTempo: hariLalu(30), nominal: 275_000_000, lunas: true },
      { id: "T2", label: "Termin 1 45%", tanggal: hariLalu(-5), jatuhTempo: hariLalu(-1), nominal: 412_500_000, lunas: false },
      { id: "T3", label: "Retensi 25%", tanggal: hariLalu(-5), jatuhTempo: hariLalu(25), nominal: 229_500_000, lunas: false },
    ],
  },
  {
    id: "INV-2026-105",
    nomor: "105/ALU/2026",
    tanggal: hariLalu(45),
    pihak: "Toko",
    nama: "Toko Bangunan Jaya",
    proyek: "Material Proyek Kanopi",
    posProyek: "Nganyang",
    uraian: "Pengadaan material baja dan kelengkapan proyek",
    termin: [
      { id: "T1", label: "Pembayaran Tunai", tanggal: hariLalu(45), jatuhTempo: hariLalu(45), nominal: 87_500_000, lunas: true },
    ],
  },
  {
    id: "INV-2026-108",
    nomor: "108/ALU/2026",
    tanggal: hariLalu(9),
    pihak: "Toko",
    nama: "UD Berkah Mandiri",
    proyek: "Instalasi AC Kantsel Rajawali",
    posProyek: "Kantor",
    uraian: "Instalasi ACVRF 5 unit dan penataan ruang panel",
    termin: [
      { id: "T1", label: "DP 30%", tanggal: hariLalu(9), jatuhTempo: hariLalu(9), nominal: 180_000_000, lunas: true },
      { id: "T2", label: "Termin 1 50%", tanggal: hariLalu(3), jatuhTempo: hariLalu(11), nominal: 300_000_000, lunas: false },
      { id: "T3", label: "Retensi 20%", tanggal: hariLalu(3), jatuhTempo: hariLalu(33), nominal: 120_000_000, lunas: false },
    ],
  },
  {
    id: "INV-2026-110",
    nomor: "110/ALU/2026",
    tanggal: hariLalu(14),
    pihak: "Kontraktor",
    nama: "CV Mitra Sejahtera",
    proyek: "Revisi Dinding SR Jasinga",
    posProyek: "SR Jasinga",
    uraian: "Pembongkaran dan revisi dinding koridor",
    termin: [
      { id: "T1", label: "DP 40%", tanggal: hariLalu(14), jatuhTempo: hariLalu(14), nominal: 96_000_000, lunas: true },
      { id: "T2", label: "Pelunasan 60%", tanggal: hariLalu(-2), jatuhTempo: hariLalu(16), nominal: 144_000_000, lunas: false },
    ],
  },
  {
    id: "INV-2026-097",
    nomor: "097/ALU/2026",
    tanggal: hariLalu(60),
    pihak: "Toko",
    nama: "Toko Listrik Mulya",
    proyek: "Instalasi Listrik Proyek Nganyang",
    posProyek: "Nganyang",
    uraian: "Pekerjaan instalasi listrik 3 fasa dan panel",
    termin: [
      { id: "T1", label: "Pembayaran 100%", tanggal: hariLalu(58), jatuhTempo: hariLalu(44), nominal: 41_750_000, lunas: true },
    ],
  },
];

export const karyawanAwal: Karyawan[] = [
  {
    id: "PGW-001",
    nama: "Sukarno",
    jabatan: "Mandor Proyek",
    lokasi: "Nganyang",
    gajiPokok: 5_400_000,
    tunjangan: 750_000,
    lembur: 620_000,
    potonganBon: 150_000,
    potonganKasbon: 0,
    periode: "2026-10",
    statusBayar: "terbayar",
    tanggalBayar: hariLalu(3),
    metodeBayar: "Transfer BCA",
  },
  {
    id: "PGW-002",
    nama: "Rina Kartika",
    jabatan: "Staff Keuangan",
    lokasi: "Kantor",
    gajiPokok: 6_200_000,
    tunjangan: 900_000,
    lembur: 0,
    potonganBon: 0,
    potonganKasbon: 500_000,
    periode: "2026-10",
    statusBayar: "terbayar",
    tanggalBayar: hariLalu(3),
    metodeBayar: "Transfer BCA",
  },
  {
    id: "PGW-003",
    nama: "Ahmad Fauzi",
    jabatan: "Mandor Proyek",
    lokasi: "Karang Ploso",
    gajiPokok: 5_200_000,
    tunjangan: 750_000,
    lembur: 480_000,
    potonganBon: 300_000,
    potonganKasbon: 0,
    periode: "2026-10",
    statusBayar: "belum",
    tanggalBayar: "",
    metodeBayar: "Tunai",
  },
  {
    id: "PGW-004",
    nama: "Bambang Sutrisno",
    jabatan: "Kuli Proyek",
    lokasi: "SR Jasinga",
    gajiPokok: 3_400_000,
    tunjangan: 350_000,
    lembur: 1_050_000,
    potonganBon: 250_000,
    potonganKasbon: 300_000,
    periode: "2026-10",
    statusBayar: "belum",
    tanggalBayar: "",
    metodeBayar: "Tunai",
  },
  {
    id: "PGW-005",
    nama: "Dedi Prasetyo",
    jabatan: "Operator Alat Berat",
    lokasi: "SR Nganjuk",
    gajiPokok: 4_100_000,
    tunjangan: 500_000,
    lembur: 890_000,
    potonganBon: 175_000,
    potonganKasbon: 0,
    periode: "2026-10",
    statusBayar: "belum",
    tanggalBayar: "",
    metodeBayar: "Transfer BRI",
  },
  {
    id: "PGW-006",
    nama: "Yoga NPM",
    jabatan: "Admin Proyek",
    lokasi: "Kantor",
    gajiPokok: 4_800_000,
    tunjangan: 600_000,
    lembur: 150_000,
    potonganBon: 0,
    potonganKasbon: 750_000,
    periode: "2026-10",
    statusBayar: "belum",
    tanggalBayar: "",
    metodeBayar: "Transfer BCA",
  },
  {
    id: "PGW-007",
    nama: "M. Hafiz",
    jabatan: "Kuli Proyek",
    lokasi: "Karang Ploso",
    gajiPokok: 3_400_000,
    tunjangan: 350_000,
    lembur: 720_000,
    potonganBon: 0,
    potonganKasbon: 250_000,
    periode: "2026-10",
    statusBayar: "belum",
    tanggalBayar: "",
    metodeBayar: "Tunai",
  },
  {
    id: "PGW-008",
    nama: "Agus Salim",
    jabatan: "Tukang Alumunium",
    lokasi: "Nganyang",
    gajiPokok: 3_700_000,
    tunjangan: 400_000,
    lembur: 560_000,
    potonganBon: 100_000,
    potonganKasbon: 0,
    periode: "2026-10",
    statusBayar: "belum",
    tanggalBayar: "",
    metodeBayar: "Tunai",
  },
];
