export const cartStyles = {
  page: "min-h-screen bg-primary",
  topbar: "sticky top-0 z-50 bg-primary-container border-b border-white/10 shadow-lg",
  topbarContent: "max-w-5xl mx-auto px-4 md:px-8 h-16 flex items-center gap-4",
  backLink: "text-white/60 hover:text-white transition-colors",
  backIcon: "material-symbols-outlined text-[28px]",
  headingContainer: "flex-1",
  heading: "text-headline-h3 font-bold text-white leading-none",
  itemCount: "text-[12px] text-white/40 mt-0.5",
  content: "max-w-5xl mx-auto px-4 md:px-8 py-8",
  empty: "flex flex-col items-center justify-center py-32 text-white/40",
  emptyIcon: "material-symbols-outlined text-[80px] mb-4",
  emptyTitle: "text-body-lg mb-2",
  emptyDescription: "text-body-md text-white/30 mb-8",
  catalogLink: "px-8 py-3 bg-secondary text-primary font-bold rounded-full hover:bg-secondary-fixed transition-all",
  grid: "grid lg:grid-cols-3 gap-8 items-start",
  itemList: "lg:col-span-2 space-y-4",
  itemCard: "bg-primary-container rounded-2xl border border-white/10 p-4",
  itemRow: "flex gap-4",
  productImage: "w-24 h-24 rounded-xl bg-cover bg-center flex-shrink-0 border border-white/10",
  itemInfo: "flex-1 min-w-0",
  itemHeader: "flex items-start justify-between gap-2",
  productInfo: "min-w-0",
  stockBadge: "inline-flex items-center gap-1 text-[11px] font-bold text-emerald-400 bg-emerald-400/10 px-2 py-0.5 rounded-full mb-1",
  stockDot: "w-1.5 h-1.5 rounded-full bg-emerald-400 inline-block",
  productTitle: "text-[14px] font-bold text-white line-clamp-2 leading-snug",
  unitPrice: "text-[12px] text-white/40 mt-0.5",
  variantBadges: "flex flex-wrap gap-1.5 mt-1.5",
  variantBadge: "inline-flex items-center gap-1 bg-white/10 text-white/70 text-[11px] px-2 py-0.5 rounded-md",
  variantKey: "text-white/40",
  deleteButton: "flex-shrink-0 p-1.5 rounded-lg text-white/25 hover:text-red-400 hover:bg-red-400/10 transition-all",
  icon: "material-symbols-outlined text-[18px]",
  quantityRow: "flex items-center justify-between mt-3",
  quantityControl: "flex items-center bg-white/5 border border-white/15 rounded-xl overflow-hidden",
  quantityButton: "w-9 h-9 flex items-center justify-center text-white/50 hover:text-white hover:bg-white/10 transition-colors",
  quantityInput: "w-12 h-9 text-center text-white text-[14px] font-bold bg-transparent border-x border-white/15 focus:outline-none",
  subtotal: "text-right",
  subtotalLabel: "text-[11px] text-white/30",
  subtotalValue: "text-[15px] font-bold text-secondary",
  noteContainer: "mt-3 pt-3 border-t border-white/5",
  noteInput: "w-full bg-white/5 border border-white/10 rounded-lg px-3 py-2 text-[12px] text-white/70 placeholder:text-white/25 focus:outline-none focus:border-secondary/50 transition-colors",
  clearContainer: "pt-2",
  clearButton: "text-[12px] text-white/30 hover:text-red-400 transition-colors flex items-center gap-1",
  smallIcon: "material-symbols-outlined text-[14px]",
  confirmClear: "flex items-center gap-3 p-3 bg-red-500/10 border border-red-500/20 rounded-xl",
  confirmText: "text-[12px] text-red-300 flex-1",
  confirmButton: "text-[12px] font-bold text-red-400 hover:text-red-300 transition-colors",
  cancelButton: "text-[12px] text-white/40 hover:text-white transition-colors",
  summaryColumn: "lg:col-span-1",
  summary: "bg-primary-container rounded-2xl border border-white/10 p-6 sticky top-24 space-y-4",
  summaryTitle: "text-[13px] font-semibold text-white/70",
  summaryItems: "space-y-2",
  summaryItem: "flex justify-between text-[12px]",
  summaryItemBlock: "",
  summaryVariants: "flex flex-wrap gap-1 mt-1",
  summaryVariantTag: "inline-flex items-center gap-1 bg-white/5 text-white/40 text-[10px] px-1.5 py-0.5 rounded",
  summaryVariantKey: "text-white/25",
  summaryItemName: "text-white/50 truncate mr-2 leading-relaxed",
  mutedQuantity: "text-white/30",
  summaryItemPrice: "text-white/80 font-medium flex-shrink-0",
  dividerSection: "border-t border-white/10 pt-3 space-y-2",
  summaryRow: "flex justify-between text-[12px]",
  label: "text-white/50",
  price: "text-white/80 font-medium",
  shipping: "text-white/40 italic",
  totalSection: "border-t border-white/10 pt-3",
  totalRow: "flex justify-between items-center",
  totalLabel: "text-[13px] font-semibold text-white",
  totalPrice: "text-[20px] font-bold text-secondary",
  totalNotice: "text-[11px] text-white/30 mt-1",
  checkoutButton: "w-full py-4 rounded-xl bg-secondary text-primary font-bold hover:bg-secondary-fixed transition-all flex items-center justify-center gap-2 text-[14px]",
  checkoutIcon: "material-symbols-outlined text-[20px]",
  continueLink: "w-full py-3 rounded-xl border border-white/15 text-white/50 hover:text-white hover:border-white/30 transition-all text-[13px] flex items-center justify-center gap-2",
  trustSection: "border-t border-white/10 pt-4",
  trustGrid: "grid grid-cols-3 gap-2 text-center",
  trustItem: "flex flex-col items-center gap-1",
  trustIcon: "material-symbols-outlined text-[20px] text-white/30",
  trustText: "text-[10px] text-white/30 leading-tight",
} as const;
