import express from "express";
import { corsMiddleware } from "./middleware/cors";
import { adminRouter, catalogRouter, checkoutRouter, portfolioRouter } from "./modules/(katalog)";
import marketingRouter from "./modules/pemasaran/router";
import customRouter from "./modules/custom/router";
import gudangRouter from "./modules/gudang/router";
export const app = express();
app.use(corsMiddleware); app.use(express.json());
app.use("/api/catalog", catalogRouter); app.use("/api/checkout", checkoutRouter); app.use("/api/portfolio", portfolioRouter);
app.use("/api/admin", adminRouter);
app.use("/api/marketing", marketingRouter);
app.use("/api/custom", customRouter);
app.use("/api/gudang", gudangRouter);
app.use((_request, response) => response.status(404).json({ success: false, error: { code: "NOT_FOUND", message: "Endpoint tidak ditemukan." } }));
