export const container = "p-10 flex-1"
export const title = "text-3xl font-bold text-white mb-2 font-headline tracking-tight"
export const subtitle = "text-white/40"
export const toggleGroup = "flex p-1 bg-white/5 rounded-pill self-start"
export const toggleButton = "px-4 py-1.5 text-[10px] font-bold rounded-pill transition-colors"
export const toggleActive = "bg-secondary text-primary shadow-sm"
export const toggleInactive = "text-white/40 hover:text-white"
