"use client";

import { useEffect, useState } from "react";
import type { LocalOrder } from "@/services/orders/types";

// Function untuk dashboard awal admin; siap disambungkan ke autentikasi dan database.
export default function AdminDashboard() {
  const [orders, setOrders] = useState<LocalOrder[]>([]);
  const [error, setError] = useState("");
  useEffect(() => { fetch(`${process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:4000/api"}/admin/orders`).then(async (response) => { const body = await response.json(); if (!response.ok) throw new Error(body.error?.message ?? "Tidak dapat memuat pesanan."); return body.data as LocalOrder[]; }).then(setOrders).catch((reason) => setError(reason.message)); }, []);
  return <main className="min-h-screen bg-primary p-6 text-white md:p-10"><div className="mx-auto max-w-6xl"><span className="text-sm font-bold uppercase tracking-widest text-secondary">Admin ALUPBESK · persiapan</span><h1 className="mt-3 text-3xl font-bold">Dashboard Admin</h1><p className="mt-2 max-w-2xl text-sm text-white/55">Halaman ini menggunakan penyimpanan lokal sementara. Sebelum produksi, aktifkan login admin dan database sesuai daftar di WARNING.md.</p><section className="mt-8 grid gap-4 sm:grid-cols-3"><div className="rounded-2xl border border-white/10 bg-white/5 p-5"><p className="text-sm text-white/50">Pesanan lokal</p><p className="mt-2 text-3xl font-bold text-secondary">{orders.length}</p></div><div className="rounded-2xl border border-white/10 bg-white/5 p-5"><p className="text-sm text-white/50">API</p><p className="mt-2 font-bold text-emerald-400">Siap lokal</p></div><div className="rounded-2xl border border-white/10 bg-white/5 p-5"><p className="text-sm text-white/50">Database</p><p className="mt-2 font-bold text-amber-300">Belum diaktifkan</p></div></section><section className="mt-8 overflow-hidden rounded-2xl border border-white/10"><div className="border-b border-white/10 p-5 font-bold">Pesanan terbaru</div>{error ? <p className="p-5 text-sm text-red-300">{error}</p> : orders.length ? <div className="divide-y divide-white/10">{orders.map((order) => <div key={order.id} className="flex flex-wrap items-center justify-between gap-3 p-5 text-sm"><div><p className="font-bold">{order.customer.name}</p><p className="mt-1 text-white/50">{order.items.length} produk · {new Intl.NumberFormat("id-ID", { style: "currency", currency: "IDR", minimumFractionDigits: 0 }).format(order.total)}</p></div><span className="rounded-full bg-secondary/15 px-3 py-1 text-xs font-bold text-secondary">{order.status}</span></div>)}</div> : <p className="p-5 text-sm text-white/45">Belum ada pesanan. Buat pesanan dari checkout untuk menguji sambungan API.</p>}</section></div></main>;
}
