// --- GudangSection ---
export const container = "p-3 sm:p-4 md:p-10 min-h-screen"
export const wrapper = "mx-auto max-w-7xl"

// --- GudangHeader ---
export const header = "mb-8 flex flex-col gap-4 md:flex-row md:items-start md:justify-between"
export const headerLeft = "flex flex-wrap items-center gap-3"
export const headerTitle = "text-xl lg:text-2xl font-extrabold text-on-surface tracking-tight uppercase font-headline"
export const badge = "rounded-full bg-secondary/10 px-3 py-1 text-[10px] font-bold text-secondary border border-secondary/20 uppercase tracking-widest"
export const headerSubtitle = "mt-1 text-xs text-on-surface-variant"
export const headerActions = "flex flex-wrap items-center gap-3"
export const tambahButton = "flex items-center gap-2 px-4 py-2.5 rounded-lg bg-secondary hover:brightness-110 text-on-secondary text-xs font-bold transition-all shadow-lg shadow-secondary/20"
export const tambahIcon = "material-symbols-outlined text-[18px]"
export const divider = "hidden md:block w-px h-8 bg-outline/20"
export const metricCard = "flex items-center gap-3 rounded-xl border border-outline/30 bg-primary-container px-4 py-3 shadow-md"
export const metricIcon = "flex h-9 w-9 items-center justify-center rounded-lg bg-secondary/10 text-secondary"
export const metricIconAlt = "flex h-9 w-9 items-center justify-center rounded-lg bg-surface-variant text-on-surface-variant"
export const metricLabel = "text-[9px] font-bold tracking-widest text-on-surface-variant uppercase"
export const metricValue = "text-lg font-bold text-secondary font-headline"
export const metricValueAlt = "text-lg font-bold text-on-surface font-headline"
export const lowStockCard = "flex items-center gap-3 rounded-xl border border-error/20 bg-error/5 px-4 py-3 shadow-md"
export const lowStockDot = "h-2.5 w-2.5 rounded-full bg-error animate-pulse shrink-0"
export const lowStockLabel = "text-[9px] font-bold tracking-widest text-error uppercase"
export const lowStockValue = "text-lg font-bold text-error font-headline"
export const iconMd = "material-symbols-outlined text-[20px]"
export const iconLg = "material-symbols-outlined text-[24px]"

// --- GudangTable ---
export const tableCard = "rounded-xl border border-outline/30 bg-primary-container shadow-2xl overflow-hidden"
export const tableToolbar = "flex flex-col gap-3 p-4 md:flex-row md:items-center md:justify-between border-b border-outline/20 bg-surface-variant/30"
export const searchWrapper = "relative flex-1 max-w-sm"
export const searchIcon = "material-symbols-outlined absolute left-3 top-1/2 -translate-y-1/2 text-on-surface-variant text-[18px] pointer-events-none"
export const searchInput = "w-full rounded-pill border border-outline/30 bg-surface-variant pl-9 pr-4 py-2 text-xs text-on-surface placeholder:text-on-surface-variant focus:ring-1 focus:ring-secondary focus:border-secondary transition-all outline-none"
export const filterWrapper = "flex items-center gap-2 shrink-0"
export const filterGroup = "flex flex-wrap items-center gap-3"
export const filterLabel = "text-[10px] text-on-surface-variant font-bold uppercase tracking-widest whitespace-nowrap"
export const filterSelect = "rounded-lg border border-outline/30 bg-surface-variant px-3 py-2 text-xs text-on-surface transition-all focus:border-secondary focus:ring-1 focus:ring-secondary outline-none"
export const tableWrapper = "overflow-x-auto"
export const table = "w-full text-left text-sm"
export const tableHead = "bg-surface-variant/50 text-[9px] lg:text-[10px] font-bold uppercase tracking-widest text-on-surface-variant border-b border-outline/20"
export const th = "px-4 lg:px-6 py-3 lg:py-4"
export const thRight = "px-4 lg:px-6 py-3 lg:py-4 text-right"
export const thHiddenSm = "px-4 lg:px-6 py-3 lg:py-4 hidden sm:table-cell"
export const thHiddenMd = "px-4 lg:px-6 py-3 lg:py-4 hidden md:table-cell"
export const tbody = "divide-y divide-outline/15"
export const emptyCell = "px-6 py-12 text-center text-on-surface-variant text-xs"
export const row = "hover:bg-surface-variant/40 transition-colors"
export const td = "px-4 lg:px-6 py-3 lg:py-5"
export const tdHiddenSm = "px-4 lg:px-6 py-3 lg:py-5 hidden sm:table-cell"
export const tdHiddenMd = "px-4 lg:px-6 py-3 lg:py-5 hidden md:table-cell"
export const tdRight = "px-4 lg:px-6 py-3 lg:py-5 text-right"
export const skuText = "font-mono text-xs font-bold text-secondary"
export const jenisText = "text-xs font-semibold text-on-surface capitalize"
export const merekBadge = "inline-block rounded bg-surface-variant px-2.5 py-1 text-[10px] font-bold text-on-surface-variant border border-outline/30 uppercase tracking-wide"
export const warnaText = "text-xs text-on-surface-variant"
export const kategoriEceranBadge = "inline-block rounded-full bg-success/10 px-2.5 py-1 text-[10px] font-bold text-success border border-success/20 uppercase tracking-wide"
export const kategoriProyekBadge = "inline-block rounded-full bg-tertiary/10 px-2.5 py-1 text-[10px] font-bold text-tertiary border border-tertiary/20 uppercase tracking-wide"
export const proyekText = "text-xs text-on-surface-variant italic"
export const satuanText = "text-[10px] text-on-surface-variant/60"
export const lokasiWrapper = "inline-flex items-center gap-1.5 text-xs text-on-surface font-medium"
export const lokasiDot = "h-1.5 w-1.5 rounded-full bg-secondary shrink-0"
export const stokWrapper = "flex items-center justify-end gap-2"
export const stokValue = "text-base font-bold text-on-surface"
export const stokValueError = "text-base font-bold text-error"
export const lowStockBadge = "rounded bg-error/10 px-1.5 py-0.5 text-[9px] font-bold text-error border border-error/20 uppercase"
export const catatanText = "rounded bg-surface-variant px-2 py-1 text-[10px] text-on-surface-variant border border-outline/20"
export const noCatatan = "text-on-surface-variant/30 text-xs"
export const aksiWrapper = "flex items-center justify-end gap-1"
export const editButton = "flex items-center justify-center w-7 h-7 rounded-lg text-on-surface-variant hover:text-secondary hover:bg-secondary/10 transition-all"
export const deleteButton = "flex items-center justify-center w-7 h-7 rounded-lg text-on-surface-variant hover:text-error hover:bg-error/10 transition-all"
export const iconSm = "material-symbols-outlined text-[16px]"
export const tableFooter = "border-t border-outline/20 px-4 lg:px-6 py-3 bg-surface-variant/30 flex items-center justify-between"
export const footerText = "text-[10px] text-on-surface-variant"
export const footerHint = "text-[10px] text-on-surface-variant/40"
export const footerAccent = "font-bold text-secondary"
export const footerEdit = "text-secondary"
export const footerDelete = "text-error"

// --- ProjectStockSummary ---
export const projectSummaryCard = "mb-6 rounded-xl border border-outline/30 bg-primary-container shadow-2xl overflow-hidden"
export const projectSummaryHeader = "px-4 lg:px-6 py-4 border-b border-outline/20 bg-surface-variant/30 flex items-center justify-between gap-3 flex-wrap"
export const projectSummaryTitle = "text-xs font-extrabold text-on-surface uppercase tracking-tight font-headline flex items-center gap-2"
export const projectSummaryGrid = "grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3 p-4 lg:p-5"
export const projectSummaryItem = "rounded-lg border border-outline/20 bg-surface-variant/40 px-4 py-3 cursor-pointer hover:border-secondary/50 transition-colors"
export const projectSummaryName = "text-xs font-bold text-on-surface flex items-center gap-2"
export const projectSummaryMeta = "text-[10px] text-on-surface-variant mt-1"
export const projectSummaryBadge = "rounded-full bg-secondary/10 px-2 py-0.5 text-[9px] font-bold text-secondary border border-secondary/20 uppercase tracking-wider"
export const projectSummaryLow = "rounded-full bg-error/10 px-2 py-0.5 text-[9px] font-bold text-error border border-error/20 uppercase tracking-wider"
export const projectSummaryCount = "rounded-full bg-surface-variant px-2 py-0.5 text-[9px] font-bold text-on-surface-variant border border-outline/30 uppercase tracking-wider"
export const formHint = "text-[10px] text-tertiary mt-1"

// --- GudangFormModal ---
export const modalBackdrop = "fixed inset-0 z-50 bg-black/60 backdrop-blur-sm flex items-center justify-center p-4"
export const modalContent = "bg-primary-container border border-outline/30 rounded-2xl p-6 shadow-2xl max-w-lg w-full text-on-surface max-h-[90vh] overflow-y-auto"
export const modalHeader = "flex items-center justify-between mb-6"
export const modalTitle = "text-base font-extrabold text-on-surface uppercase tracking-tight font-headline"
export const modalSubtitle = "text-[10px] text-on-surface-variant mt-0.5"
export const modalCloseButton = "text-on-surface-variant hover:text-on-surface transition-colors p-1 rounded-lg hover:bg-surface-variant"
export const closeIcon = "material-symbols-outlined text-[20px]"
export const formGroup = "space-y-4"
export const formLabel = "text-[10px] font-bold text-on-surface-variant uppercase tracking-widest mb-1.5 block"
export const required = "text-error"
export const formInput = "w-full rounded-lg border border-outline/30 bg-surface-variant px-3 py-2.5 text-sm text-on-surface placeholder:text-on-surface-variant/40 focus:border-secondary focus:ring-1 focus:ring-secondary outline-none transition-all"
export const formError = "text-error text-[10px] mt-1"
export const formGrid = "grid grid-cols-2 gap-3"
export const formTextarea = "w-full rounded-lg border border-outline/30 bg-surface-variant px-3 py-2.5 text-sm text-on-surface placeholder:text-on-surface-variant/40 focus:border-secondary focus:ring-1 focus:ring-secondary outline-none transition-all resize-none"
export const modalFooter = "flex items-center justify-end gap-3 mt-6 pt-4 border-t border-outline/20"
export const cancelButton = "px-4 py-2.5 rounded-lg bg-surface-variant hover:bg-surface-container-high text-on-surface-variant hover:text-on-surface text-sm font-medium transition-all border border-outline/30"
export const saveButton = "px-5 py-2.5 rounded-lg bg-secondary hover:brightness-110 text-on-secondary text-sm font-bold transition-all shadow-lg shadow-secondary/20"

// --- DeleteConfirmModal ---
export const deleteModalContent = "bg-primary-container border border-outline/30 rounded-2xl p-6 shadow-2xl max-w-md w-full text-on-surface"
export const deleteIconWrapper = "flex items-center justify-center w-12 h-12 rounded-full bg-error/10 border border-error/20 mx-auto mb-4"
export const deleteModalTitle = "text-base font-extrabold text-on-surface uppercase tracking-tight font-headline mb-2"
export const deleteModalText = "text-xs text-on-surface-variant leading-relaxed"
export const itemCard = "mt-3 rounded-lg border border-outline/20 bg-surface-variant/40 px-4 py-3 text-left"
export const itemSkuWrapper = "flex items-center gap-2 mb-1"
export const itemSku = "font-mono text-xs font-bold text-secondary"
export const itemMerekBadge = "rounded bg-surface-variant px-2 py-0.5 text-[9px] font-bold text-on-surface-variant border border-outline/20 uppercase"
export const itemDetail = "text-[10px] text-on-surface-variant capitalize"
export const itemStok = "text-[10px] text-on-surface-variant mt-0.5"
export const itemStokValue = "font-bold text-on-surface"
export const warningText = "text-[10px] text-error/70 mt-3"
export const deleteModalFooter = "flex items-center gap-3"
export const deleteCancelButton = "flex-1 px-4 py-2.5 rounded-lg bg-surface-variant hover:bg-surface-container-high text-on-surface-variant hover:text-on-surface text-sm font-medium transition-all border border-outline/30"
export const deleteConfirmButton = "flex-1 px-4 py-2.5 rounded-lg bg-error hover:brightness-110 text-white text-sm font-bold transition-all shadow-lg shadow-error/20"

// --- LoadingSkeleton ---
export const skeleton = "bg-surface-variant rounded-xl animate-pulse"

// --- MovementHistorySection ---
export const movementHeader = "p-4 lg:p-6 border-b border-outline/20 bg-surface-variant/30 flex flex-col gap-4 md:flex-row md:items-start md:justify-between"
export const movementTitle = "text-sm font-extrabold text-on-surface uppercase tracking-tight font-headline"
export const movementSubtitle = "text-[10px] text-on-surface-variant mt-0.5"
export const movementMetrics = "flex flex-wrap items-center gap-3"
export const movementMetricCard = "flex items-center gap-2.5 rounded-xl border border-outline/30 bg-primary-container px-4 py-2.5 shadow-md"
export const movementDot = "h-2.5 w-2.5 rounded-full shrink-0"
export const movementMetricLabel = "text-[9px] font-bold tracking-widest text-on-surface-variant uppercase"
export const movementMetricValue = "text-sm font-bold text-on-surface font-headline"
export const tanggalText = "text-xs text-on-surface font-medium whitespace-nowrap"
export const tipeMasukBadge = "inline-block rounded-full bg-success/10 px-2.5 py-1 text-[10px] font-bold text-success border border-success/20 uppercase tracking-wide"
export const tipeKeluarBadge = "inline-block rounded-full bg-error/10 px-2.5 py-1 text-[10px] font-bold text-error border border-error/20 uppercase tracking-wide"
export const jumlahMasukText = "text-sm font-bold text-success"
export const jumlahKeluarText = "text-sm font-bold text-error"
export const movementDetail = "text-xs text-on-surface-variant"
