import type { GudangItem } from "./types";

// Data mock diletakkan di service layer, bukan di component.
// Ketika sistem dihubungkan ke Supabase/API, hanya file ini yang perlu diubah —
// tidak ada UI component yang perlu dirombak.
const MOCK_GUDANG_ITEMS: GudangItem[] = [
  {
    id: "gd-101",
    sku: "HND-DKS-BK-001",
    jenisBarang: "handle",
    merek: "DEKSON",
    warna: "Black Matte",
    seksiLokasi: "Seksi 1",
    stok: 145,
    minStok: 20,
    catatan: "Rak utama depan",
  },
  {
    id: "gd-102",
    sku: "MRT-SLD-SS-808",
    jenisBarang: "mortise",
    merek: "SOLID",
    warna: "Stainless Steel",
    seksiLokasi: "Seksi 2",
    stok: 6,
    minStok: 15,
    catatan: "Restock mingguan diajukan",
  },
  {
    id: "gd-103",
    sku: "HND-PLM-SB-302",
    jenisBarang: "handle",
    merek: "PALOMA",
    warna: "Satin Brass",
    seksiLokasi: "Rak B (Atas)",
    stok: 38,
    minStok: 10,
    catatan: "Beda rak dari Seksi 3",
  },
  {
    id: "gd-104",
    sku: "MRT-BLC-SN-011",
    jenisBarang: "mortise",
    merek: "BELOCCA",
    warna: "SN/CP",
    seksiLokasi: "Seksi 3",
    stok: 3,
    minStok: 10,
    catatan: "Periksa segel dus",
  },
  {
    id: "gd-105",
    sku: "HND-KND-SC-501",
    jenisBarang: "handle",
    merek: "KEND",
    warna: "Silver Chrome",
    seksiLokasi: "Seksi 1",
    stok: 82,
    minStok: 15,
  },
  {
    id: "gd-106",
    sku: "MRT-RDO-GD-909",
    jenisBarang: "mortise",
    merek: "RED ORCHAD",
    warna: "Gold",
    seksiLokasi: "Seksi 2",
    stok: 4,
    minStok: 12,
    catatan: "Posisi rak paling atas",
  },
  {
    id: "gd-107",
    sku: "HND-HMP-BK-772",
    jenisBarang: "handle",
    merek: "HAMPTON",
    warna: "Black",
    seksiLokasi: "Rak B (Atas)",
    stok: 110,
    minStok: 25,
  },
  {
    id: "gd-108",
    sku: "MRT-ALF-CR-104",
    jenisBarang: "mortise",
    merek: "ALFIS",
    warna: "Chrome",
    seksiLokasi: "Seksi 3",
    stok: 64,
    minStok: 15,
    catatan: "Beda rak dengan varian Black",
  },
  {
    id: "gd-109",
    sku: "HND-DKS-GD-220",
    jenisBarang: "handle",
    merek: "DEKSON",
    warna: "Gold",
    seksiLokasi: "Seksi 2",
    stok: 57,
    minStok: 20,
  },
  {
    id: "gd-110",
    sku: "MRT-PLM-BK-415",
    jenisBarang: "mortise",
    merek: "PALOMA",
    warna: "Black",
    seksiLokasi: "Seksi 1",
    stok: 8,
    minStok: 12,
    catatan: "Stok terakhir — segera reorder",
  },
  {
    id: "gd-111",
    sku: "HND-KND-GD-318",
    jenisBarang: "handle",
    merek: "KEND",
    warna: "Gold",
    seksiLokasi: "Seksi 3",
    stok: 33,
    minStok: 10,
  },
  {
    id: "gd-112",
    sku: "MRT-HMP-SS-660",
    jenisBarang: "mortise",
    merek: "HAMPTON",
    warna: "Stainless Steel",
    seksiLokasi: "Rak B (Atas)",
    stok: 19,
    minStok: 20,
    catatan: "Beda rak",
  },
];

// Async agar mudah dimigrasi ke pemanggilan API/database tanpa mengubah caller
export async function getGudangItems(): Promise<GudangItem[]> {
  return Promise.resolve(MOCK_GUDANG_ITEMS);
}
