// --- Laporan section ---
export const container = "p-3 sm:p-4 md:p-10 min-h-screen"
export const wrapper = "mx-auto max-w-7xl"
export const header = "mb-8 flex flex-col gap-4 md:flex-row md:items-start md:justify-between"
export const headerTitle = "text-xl lg:text-2xl font-extrabold text-on-surface tracking-tight uppercase font-headline"
export const badge = "rounded-full bg-secondary/10 px-3 py-1 text-[10px] font-bold text-secondary border border-secondary/20 uppercase tracking-widest"
export const headerSubtitle = "mt-1 text-xs text-on-surface-variant"

export const metricsGrid = "grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 mb-6"
export const metricCard = "rounded-xl border border-outline/30 bg-primary-container p-4 shadow-md"
export const metricLabel = "text-[9px] font-bold tracking-widest text-on-surface-variant uppercase"
export const metricValue = "mt-1 text-lg lg:text-xl font-bold text-on-surface font-headline"

export const chartsRow = "grid grid-cols-1 lg:grid-cols-3 gap-4 mb-6"
export const revenueChart = "rounded-xl border border-outline/30 bg-primary-container shadow-2xl p-5 lg:col-span-2"
export const revenueChartHeader = "flex flex-col gap-3 md:flex-row md:items-start md:justify-between mb-6"
export const sectionTitle = "text-sm font-bold text-on-surface uppercase tracking-wider font-headline"
export const sectionSubtitle = "text-[11px] text-on-surface-variant"
export const toggleGroup = "flex items-center gap-1 rounded-lg bg-surface-variant p-1"
export const toggleButton = "px-2.5 py-1.5 rounded-md text-[10px] font-bold uppercase tracking-wider transition-all"
export const toggleActive = "bg-secondary text-on-secondary shadow"
export const toggleInactive = "text-on-surface-variant hover:text-on-surface"
export const chartArea = "flex items-end gap-1.5 h-48 lg:h-56 border-b border-outline/20"
export const bar = "flex-1 rounded-t-md bg-secondary/60 hover:bg-secondary transition-colors"
export const chartLabels = "flex items-center gap-1.5 mt-2"
export const chartLabel = "flex-1 text-center text-[9px] text-on-surface-variant uppercase tracking-wider"

export const expenseCard = "rounded-xl border border-outline/30 bg-primary-container shadow-2xl p-5"
export const expenseCardHeader = "mb-5"
export const donutContainer = "relative mx-auto mb-5 h-40 w-40"
export const donutSvg = "h-full w-full -rotate-90"
export const donutCenter = "absolute inset-0 flex flex-col items-center justify-center"
export const donutCenterValue = "text-xl font-extrabold text-on-surface font-headline"
export const donutCenterLabel = "text-[9px] text-on-surface-variant uppercase tracking-widest max-w-[80px] text-center"
export const expenseList = "space-y-2.5"
export const expenseItem = "flex items-center justify-between"
export const expenseItemLeft = "flex items-center gap-2"
export const expenseDot = "h-2.5 w-2.5 rounded-full shrink-0"
export const expenseLabel = "text-xs text-on-surface"
export const expenseValue = "text-xs font-bold text-on-surface-variant"

export const tableCard = "rounded-xl border border-outline/30 bg-primary-container shadow-2xl overflow-hidden"
export const tableHeader = "flex items-center justify-between p-4 border-b border-outline/20 bg-surface-variant/30"
export const tableTitle = "text-sm font-bold text-on-surface uppercase tracking-wider font-headline"
export const tableWrapper = "overflow-x-auto"
export const table = "w-full text-left text-sm"
export const tableHead = "bg-surface-variant/50 text-[9px] lg:text-[10px] font-bold uppercase tracking-widest text-on-surface-variant border-b border-outline/20"
export const tableHeadCell = "px-4 py-3"
export const tableHeadCellRight = "text-right"
export const tableRow = "border-b border-outline/10 transition-colors hover:bg-surface-variant/30"
export const tableCell = "px-4 py-3 text-xs text-on-surface"
export const tableCellHighlight = "font-bold text-success"
export const tableCellSecondary = "text-on-surface-variant"
export const statusBadge = "inline-flex items-center gap-1 rounded-full border border-secondary/20 bg-secondary/10 px-2 py-0.5 text-[9px] font-bold uppercase tracking-widest text-secondary"
export const emptyState = "px-4 py-10 text-center text-xs text-on-surface-variant"
