export const container = "p-3 sm:p-4 md:p-10 min-h-screen"
export const wrapper = "mx-auto max-w-7xl"

export const header = "mb-8 flex flex-col gap-4 md:flex-row md:items-start md:justify-between"
export const headerLeft = "flex flex-wrap items-center gap-3"
export const headerTitle = "text-xl lg:text-2xl font-extrabold text-on-surface tracking-tight uppercase font-headline"
export const badge = "rounded-full bg-secondary/10 px-3 py-1 text-[10px] font-bold text-secondary border border-secondary/20 uppercase tracking-widest"
export const headerSubtitle = "mt-1 text-xs text-on-surface-variant"

export const metricGrid = "grid grid-cols-1 md:grid-cols-3 gap-4 mb-8"
export const metricCard = "rounded-xl border border-outline/30 bg-primary-container px-4 py-3 shadow-md"
export const metricLabel = "text-[9px] font-bold tracking-widest text-on-surface-variant uppercase"
export const metricValue = "text-lg font-bold font-headline"

export const filterBar = "flex flex-wrap items-center gap-3 mb-6"
export const searchWrapper = "relative flex-1 max-w-sm"
export const searchIcon = "material-symbols-outlined absolute left-3 top-1/2 -translate-y-1/2 text-on-surface-variant text-[18px] pointer-events-none"
export const searchInput = "w-full rounded-pill border border-outline/30 bg-surface-variant pl-9 pr-4 py-2 text-xs text-on-surface placeholder:text-on-surface-variant focus:ring-1 focus:ring-secondary focus:border-secondary transition-all outline-none"
export const filterCard = "bg-primary-container border border-outline/30 p-3 rounded-xl flex items-center justify-between cursor-pointer hover:border-secondary/50 transition-colors relative min-w-[180px]"
export const filterCardLabel = "text-on-surface-variant text-xs font-semibold"
export const expandIcon = "material-symbols-outlined text-[16px] text-on-surface-variant"
export const dropdown = "absolute top-full left-0 right-0 mt-2 bg-primary-container border border-outline/30 rounded-xl shadow-xl z-10 overflow-hidden"
export const dropdownItem = "w-full text-left px-4 py-3 text-xs text-on-surface hover:bg-surface-variant transition-colors"
export const dropdownActive = "text-secondary font-bold"
export const dropdownInactive = "text-on-surface-variant"

export const tableCard = "rounded-xl border border-outline/30 bg-primary-container shadow-2xl overflow-hidden"
export const tableWrapper = "overflow-x-auto"
export const table = "w-full text-left text-sm"
export const tableHead = "bg-surface-variant/50 text-[9px] lg:text-[10px] font-bold uppercase tracking-widest text-on-surface-variant border-b border-outline/20"
export const th = "px-4 lg:px-6 py-3 lg:py-4"
export const thRight = "px-4 lg:px-6 py-3 lg:py-4 text-right"
export const thHiddenSm = "px-4 lg:px-6 py-3 lg:py-4 hidden sm:table-cell"
export const tbody = "divide-y divide-outline/15"
export const emptyCell = "px-6 py-12 text-center text-on-surface-variant text-xs"
export const row = "hover:bg-surface-variant/40 transition-colors"
export const td = "px-4 lg:px-6 py-3 lg:py-5"
export const tdHiddenSm = "px-4 lg:px-6 py-3 lg:py-5 hidden sm:table-cell"
export const tdRight = "px-4 lg:px-6 py-3 lg:py-5 text-right"

export const orderIdText = "font-mono text-xs font-bold text-secondary"
export const segmenBadge = "mt-1.5 inline-block rounded-full px-2 py-0.5 text-[9px] font-bold uppercase tracking-wider"
export const statusBadge = "inline-flex items-center gap-1.5 px-2.5 py-1 rounded-pill text-[10px] font-bold uppercase tracking-wider"
export const statusDot = "w-1.5 h-1.5 rounded-full"
export const jumlahBaris = "text-xs text-on-surface-variant"
export const totalText = "text-sm font-bold text-on-surface whitespace-nowrap"

export const aksiWrapper = "flex items-center justify-end gap-1"
export const actionButton = "px-3 py-1.5 rounded-lg text-[10px] font-bold uppercase tracking-wide transition-all"
export const processButton = "bg-secondary text-on-secondary hover:brightness-110 shadow-lg shadow-secondary/20"
export const completeButton = "bg-success/10 text-success border border-success/20 hover:bg-success/20"
export const doneBadge = "text-[10px] font-bold text-success uppercase tracking-wide"

export const pagination = "flex flex-col gap-3 sm:flex-row items-center justify-between mt-6"
export const paginationText = "text-[10px] text-on-surface-variant"
export const paginationHighlight = "font-bold text-secondary"
export const paginationButtons = "flex gap-2"
export const paginationNav = "px-4 py-2 rounded-pill border border-outline/30 text-[10px] font-bold hover:bg-surface-variant hover:text-on-surface transition-all disabled:opacity-30 disabled:cursor-not-allowed"
export const pageButton = "w-8 h-8 rounded-full text-[10px] font-bold flex items-center justify-center transition-all"
export const activePage = "bg-secondary text-on-secondary shadow-lg shadow-secondary/20"
export const inactivePage = "border border-outline/30 hover:border-secondary"

export const icon = "material-symbols-outlined"

export const modalOverlay = "fixed inset-0 bg-black/60 backdrop-blur-sm flex items-center justify-center z-50 animate-fadeIn"
export const modalContent = "bg-primary-container border border-outline/30 rounded-2xl p-6 w-full max-w-lg max-h-[90vh] overflow-y-auto shadow-2xl"
export const modalHeader = "flex items-center justify-between mb-5"
export const modalTitle = "text-base font-extrabold text-on-surface uppercase tracking-tight font-headline"
export const modalSubtitle = "text-[10px] text-on-surface-variant mt-0.5"
export const modalCloseButton = "text-on-surface-variant hover:text-on-surface transition-colors p-1 rounded-lg hover:bg-surface-variant"
export const closeIcon = "material-symbols-outlined text-[20px]"

export const confirmIcon = "flex items-center justify-center w-12 h-12 rounded-full bg-secondary/10 border border-secondary/20 mx-auto mb-4"
export const confirmTitle = "text-base font-extrabold text-on-surface text-center font-headline mb-2"
export const confirmText = "text-xs text-on-surface-variant text-center mb-6 leading-relaxed"
export const actionsWrapper = "flex gap-3"
export const primaryButton = "flex-1 py-2.5 bg-secondary text-on-secondary font-bold rounded-lg text-xs uppercase tracking-wide hover:brightness-110 transition-all flex items-center justify-center gap-2"
export const secondaryButton = "flex-1 py-2.5 border border-outline/30 rounded-lg text-on-surface-variant font-bold text-xs uppercase tracking-wide hover:bg-surface-variant transition-colors"

export const itemCard = "mt-3 rounded-lg border border-outline/20 bg-surface-variant/40 px-4 py-3"
export const itemSkuWrapper = "flex items-center gap-2 mb-1"
export const itemTitle = "font-mono text-xs font-bold text-secondary"
export const itemQty = "text-[10px] text-on-surface-variant mt-0.5"
export const itemSubtotal = "text-xs font-bold text-on-surface mt-0.5"

export const infoRow = "flex justify-between py-1.5 text-xs"
export const infoLabel = "text-on-surface-variant"
export const infoValue = "text-on-surface font-bold text-right max-w-[60%]"

export const totalRow = "flex justify-between items-center py-3 border-t border-outline/20 mt-3"
export const totalLabel = "text-xs font-bold text-on-surface"
export const totalValue = "text-base font-bold text-secondary font-headline"

export const noticeText = "text-[10px] text-on-surface-variant mt-2"
