// --- Kas section ---
export const container = "p-3 sm:p-4 md:p-10 min-h-screen"
export const wrapper = "mx-auto max-w-7xl"

// --- Header ---
export const header = "mb-8 flex flex-col gap-4 md:flex-row md:items-start md:justify-between"
export const headerTitle = "text-xl lg:text-2xl font-extrabold text-on-surface tracking-tight uppercase font-headline"
export const badge = "rounded-full bg-secondary/10 px-3 py-1 text-[10px] font-bold text-secondary border border-secondary/20 uppercase tracking-widest"
export const headerSubtitle = "mt-1 text-xs text-on-surface-variant"

// --- Metric cards ---
export const cardGrid = "grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4 mb-8"
export const metricCard = "rounded-xl border border-outline/30 bg-primary-container p-4 shadow-md flex items-center gap-3"
export const metricIcon = "flex h-9 w-9 items-center justify-center rounded-lg bg-secondary/10 text-secondary shrink-0"
export const metricIconOut = "flex h-9 w-9 items-center justify-center rounded-lg bg-error/10 text-error shrink-0"
export const metricLabel = "text-[9px] font-bold tracking-widest text-on-surface-variant uppercase"
export const metricValue = "text-lg lg:text-xl font-bold text-on-surface font-headline"

// --- Layout: form + riwayat ---
export const grid = "grid grid-cols-1 lg:grid-cols-3 gap-4"
export const formCard = "rounded-xl border border-outline/30 bg-primary-container shadow-2xl p-5"
export const formTitle = "text-sm font-bold text-on-surface uppercase tracking-wider font-headline"
export const formSubtitle = "text-[11px] text-on-surface-variant"
export const fieldLabel = "block text-xs sm:text-[10px] font-bold tracking-widest text-on-surface-variant uppercase mb-1"
export const input = "w-full rounded-lg border border-outline/30 bg-surface-variant px-3 py-2 text-base sm:text-xs text-on-surface placeholder:text-on-surface-variant focus:ring-1 focus:ring-secondary focus:border-secondary transition-all outline-none"
export const toggleGroup = "flex items-center gap-1 rounded-lg bg-surface-variant p-1"
export const toggleButton = "flex flex-1 items-center justify-center gap-1.5 rounded-md px-3 py-2 text-[10px] font-bold uppercase tracking-wider transition-all"
export const toggleActiveMasuk = "bg-success/20 text-success shadow"
export const toggleActiveKeluar = "bg-error/20 text-error shadow"
export const toggleInactive = "text-on-surface-variant hover:text-on-surface"
export const submitButton = "w-full flex items-center justify-center gap-2 px-4 py-2.5 rounded-lg bg-secondary hover:brightness-110 text-on-secondary text-xs font-bold transition-all shadow-lg shadow-secondary/20 disabled:opacity-50 disabled:cursor-not-allowed"
export const tableCard = "rounded-xl border border-outline/30 bg-primary-container shadow-2xl overflow-hidden lg:col-span-2"
export const tableToolbar = "flex flex-col gap-3 p-4 md:flex-row md:items-center md:justify-between border-b border-outline/20 bg-surface-variant/30"
export const tableTitle = "text-sm font-bold text-on-surface uppercase tracking-wider font-headline"
export const tableWrapper = "w-full overflow-x-auto"
export const table = "w-full min-w-[760px] text-left text-sm"
export const tableHead = "bg-surface-variant/50 text-[9px] lg:text-[10px] font-bold uppercase tracking-widest text-on-surface-variant border-b border-outline/20"
export const tableHeadCell = "px-4 py-3"
export const tableRow = "border-b border-outline/10 transition-colors hover:bg-surface-variant/30"
export const tableCell = "px-4 py-3 text-xs text-on-surface"
export const badgeBase = "inline-flex items-center gap-1 rounded-full border px-2 py-0.5 text-[9px] font-bold uppercase tracking-widest"
export const masukBadge = "bg-success/10 text-success border-success/20"
export const keluarBadge = "bg-error/10 text-error border-error/20"
export const jumlahMasuk = "font-bold text-success"
export const jumlahKeluar = "font-bold text-error"
export const actionButton = "flex h-7 w-7 items-center justify-center rounded-lg border border-outline/30 text-on-surface-variant hover:text-on-surface transition-colors"
export const actionButtonDanger = "flex h-7 w-7 items-center justify-center rounded-lg border border-error/30 text-error hover:bg-error/10 transition-colors"
export const emptyState = "px-4 py-10 text-center text-xs text-on-surface-variant"

// --- Modal (tambah/ubah/hapus transaksi) ---
export const modalOverlay = "fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-3 sm:p-4 animate-fadeIn"
export const modalContent = "w-full max-w-md rounded-2xl border border-outline/30 bg-primary-container p-4 sm:p-6 shadow-2xl max-h-[calc(100dvh-1.5rem)] sm:max-h-[90vh] overflow-y-auto"
export const modalHeader = "mb-5 flex items-start justify-between"
export const modalTitle = "text-sm font-bold text-on-surface uppercase tracking-wider font-headline"
export const modalSubtitle = "text-[11px] text-on-surface-variant"
export const modalCloseButton = "flex h-8 w-8 items-center justify-center rounded-lg text-on-surface-variant hover:text-on-surface transition-colors"
export const confirmIcon = "mb-3 flex items-center justify-center"
export const confirmTitle = "mb-2 text-center text-base font-bold text-on-surface"
export const confirmText = "mb-6 text-center text-xs text-on-surface-variant"
export const actionsWrapper = "flex items-center justify-end gap-3"
export const secondaryButton = "rounded-lg border border-outline/30 px-4 py-2.5 text-xs font-bold text-on-surface transition-all hover:bg-surface-variant disabled:opacity-50"
export const primaryButton = "flex items-center justify-center gap-2 rounded-lg bg-secondary px-4 py-2.5 text-xs font-bold text-on-secondary transition-all shadow-lg shadow-secondary/20 hover:brightness-110 disabled:opacity-50"
export const dangerButton = "flex items-center justify-center gap-2 rounded-lg bg-error px-4 py-2.5 text-xs font-bold text-on-error transition-all hover:brightness-110 disabled:opacity-50"
